# netlify.toml

[build]
  command = "./gradlew build"
  publish = "build/"

# Si votre projet nécessite des variables d'environnement
[context.production.environment]
  JAVA_OPTS = "-Dspring.profiles.active=production"

# Si vous avez des redirections à définir
