# netlify.toml

[build]
  command = "bash ./install-ant.sh && ant build"
  publish = "dist/"

# Si votre projet nécessite des variables d'environnement
[context.production.environment]
  JAVA_OPTS = "-Dspring.profiles.active=production"

# Si vous avez des redirections à définir
